import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 'hsr-01',
    slug: 'high-speed-roll-doors',
    name: 'High-Speed Roll Doors',
    category: 'industrial-doors',
    subcategory: 'High-Speed Doors',
    shortDescription: 'Industrial high-speed doors for rapid access and energy efficiency',
    fullDescription: 'Our high-speed roll doors are engineered for high-traffic industrial environments requiring rapid opening and closing cycles. Built with durable materials and advanced control systems, these doors improve operational efficiency while maintaining environmental control.',
    features: [
      'Opening speed up to 2.5 m/s',
      'Self-repairing fabric design',
      'Wind-resistant construction',
      'Integrated safety sensors',
      'Variable frequency drive',
      'Remote monitoring capability',
    ],
    specifications: [
      { label: 'Max Width', value: '6000', unit: 'mm' },
      { label: 'Max Height', value: '6000', unit: 'mm' },
      { label: 'Opening Speed', value: '2.5', unit: 'm/s' },
      { label: 'Closing Speed', value: '1.5', unit: 'm/s' },
      { label: 'Operating Cycles', value: '200000', unit: 'cycles/year' },
      { label: 'Motor Power', value: '1.5', unit: 'kW' },
    ],
    applications: [
      'Manufacturing facilities',
      'Food processing plants',
      'Pharmaceutical clean rooms',
      'Cold storage warehouses',
      'Logistics centers',
    ],
    benefits: [
      'Reduced energy costs through quick operation',
      'Improved temperature control',
      'Enhanced safety with multiple sensors',
      'Minimal maintenance requirements',
      'Increased productivity with fast access',
    ],
    images: [
      { url: '/images/products/high-speed-door-1.jpg', alt: 'High-Speed Roll Door - Main View', isMain: true },
      { url: '/images/products/high-speed-door-2.jpg', alt: 'High-Speed Roll Door - Installation' },
      { url: '/images/products/high-speed-door-3.jpg', alt: 'High-Speed Roll Door - Control Panel' },
    ],
    metaTitle: 'High-Speed Roll Doors | Industrial Doors | Bevcon Solutions',
    metaDescription: 'High-performance industrial high-speed roll doors for rapid access. Opening speeds up to 2.5 m/s with self-repairing design and advanced safety features.',
  },
  {
    id: 'hdl-01',
    slug: 'hydraulic-dock-levelers',
    name: 'Hydraulic Dock Levelers',
    category: 'loading-bay',
    subcategory: 'Dock Levelers',
    shortDescription: 'Heavy-duty hydraulic dock levelers for safe and efficient loading operations',
    fullDescription: 'Our hydraulic dock levelers provide smooth, reliable bridging between dock and vehicle, facilitating safe and efficient loading and unloading operations. Designed for heavy-duty use with advanced safety features.',
    features: [
      'Hydraulic operation for smooth movement',
      '10-ton capacity standard (higher available)',
      'Automatic lip extension',
      'Safety velocity fuses',
      'Maintenance-free design',
      'Weather sealing included',
    ],
    specifications: [
      { label: 'Capacity', value: '10000', unit: 'kg' },
      { label: 'Platform Width', value: '2100', unit: 'mm' },
      { label: 'Platform Length', value: '2500', unit: 'mm' },
      { label: 'Vertical Travel', value: '400', unit: 'mm' },
      { label: 'Lip Length', value: '500', unit: 'mm' },
      { label: 'Cycle Time', value: '30', unit: 'seconds' },
    ],
    applications: [
      'Warehouse loading docks',
      'Distribution centers',
      'Manufacturing facilities',
      'Cold storage facilities',
      'Freight terminals',
    ],
    benefits: [
      'Improved loading efficiency',
      'Enhanced worker safety',
      'Reduced vehicle and dock damage',
      'Weather protection',
      'Long service life with minimal maintenance',
    ],
    images: [
      { url: '/images/products/dock-leveler-1.jpg', alt: 'Hydraulic Dock Leveler - Main View', isMain: true },
      { url: '/images/products/dock-leveler-2.jpg', alt: 'Hydraulic Dock Leveler - In Use' },
      { url: '/images/products/dock-leveler-3.jpg', alt: 'Hydraulic Dock Leveler - Components' },
    ],
    metaTitle: 'Hydraulic Dock Levelers | Docking Equipment | Bevcon Solutions',
    metaDescription: 'Heavy-duty hydraulic dock levelers with 10-ton capacity. Smooth operation, automatic lip extension, and advanced safety features for efficient loading operations.',
  },
  {
    id: 'asd-01',
    slug: 'automatic-sliding-doors',
    name: 'Automatic Sliding Doors',
    category: 'automatic-doors',
    subcategory: 'Sliding Doors',
    shortDescription: 'Energy-efficient automatic sliding doors for commercial and industrial entrances',
    fullDescription: 'Premium automatic sliding door systems combining elegant design with reliable operation. Suitable for high-traffic commercial and industrial applications with advanced sensor technology and energy-saving features.',
    features: [
      'Smooth and quiet operation',
      'Adjustable opening/closing speed',
      'Safety sensors (IR and microwave)',
      'Low energy consumption',
      'Customizable glass and frame options',
      'Emergency breakout functionality',
    ],
    specifications: [
      { label: 'Max Opening Width', value: '2000', unit: 'mm per leaf' },
      { label: 'Max Door Height', value: '3000', unit: 'mm' },
      { label: 'Opening Speed', value: '0.5', unit: 'm/s' },
      { label: 'Motor Power', value: '120', unit: 'W' },
      { label: 'Operating Cycles', value: '500000', unit: 'cycles' },
      { label: 'Ambient Temperature', value: '-20 to +50', unit: '°C' },
    ],
    applications: [
      'Corporate offices',
      'Shopping malls',
      'Hospitals and healthcare',
      'Hotels and hospitality',
      'Industrial facilities',
    ],
    benefits: [
      'Hands-free operation for hygiene',
      'Energy efficiency with tight sealing',
      'Accessibility compliance',
      'Modern aesthetic appeal',
      'Reliable operation in high-traffic areas',
    ],
    images: [
      { url: '/images/products/automatic-sliding-door-1.jpg', alt: 'Automatic Sliding Door - Main View', isMain: true },
      { url: '/images/products/automatic-sliding-door-2.jpg', alt: 'Automatic Sliding Door - Open' },
      { url: '/images/products/automatic-sliding-door-3.jpg', alt: 'Automatic Sliding Door - Control System' },
    ],
    metaTitle: 'Automatic Sliding Doors | Entrance Automation | Bevcon Solutions',
    metaDescription: 'Energy-efficient automatic sliding door systems for commercial and industrial entrances. Smooth operation with advanced safety features and customizable design.',
  },
  {
    id: 'rc-01',
    slug: 'roller-conveyors',
    name: 'Conveying Systems',
    category: 'material-handling',
    subcategory: 'Conveyors',
    shortDescription: 'Heavy-duty conveying systems for efficient material transport',
    fullDescription: 'Robust conveying systems designed for transporting various products in manufacturing, warehousing, and distribution facilities. Available in gravity and powered configurations to suit different operational needs.',
    features: [
      'Heavy-duty roller construction',
      'Modular design for easy expansion',
      'Variable speed control (powered models)',
      'Low maintenance requirements',
      'Customizable roller spacing',
      'Corrosion-resistant options available',
    ],
    specifications: [
      { label: 'Load Capacity', value: '500', unit: 'kg/m' },
      { label: 'Roller Diameter', value: '50-89', unit: 'mm' },
      { label: 'Conveyor Width', value: '300-1200', unit: 'mm' },
      { label: 'Speed', value: '0.5-1.5', unit: 'm/s' },
      { label: 'Motor Power', value: '0.75-2.2', unit: 'kW' },
      { label: 'Frame Material', value: 'Mild Steel / Stainless Steel', unit: '' },
    ],
    applications: [
      'Warehouse distribution',
      'Manufacturing assembly lines',
      'Package handling',
      'E-commerce fulfillment',
      'Airport baggage handling',
    ],
    benefits: [
      'Increased material handling efficiency',
      'Reduced manual labor',
      'Scalable system design',
      'Durable construction',
      'Energy-efficient operation',
    ],
    images: [
      { url: '/images/products/roller-conveyor-1.jpg', alt: 'Roller Conveyor - Main View', isMain: true },
      { url: '/images/products/roller-conveyor-2.jpg', alt: 'Roller Conveyor - Installation' },
      { url: '/images/products/roller-conveyor-3.jpg', alt: 'Roller Conveyor - Detail' },
    ],
    metaTitle: 'Conveying Systems | Material Handling | Bevcon Solutions',
    metaDescription: 'Heavy-duty conveying systems for efficient material transport. Modular design with customizable configurations for warehousing and manufacturing.',
  },
];

export const productCategories = [
  {
    id: 'automatic-doors',
    name: 'Automatic Doors',
    description: 'Entrance automation solutions for commercial and industrial facilities',
    icon: 'door-open',
    image: '/images/categories/automatic-doors.jpg',
  },
  {
    id: 'industrial-doors',
    name: 'Industrial Doors',
    description: 'High-performance doors for demanding industrial environments',
    icon: 'factory',
    image: '/images/categories/industrial-doors.jpg',
  },
  {
    id: 'loading-bay',
    name: 'Docking Equipment / Dock Levellers',
    description: 'Complete solutions for efficient dock operations',
    icon: 'package',
    image: '/images/categories/loading-bay.jpg',
  },
  {
    id: 'material-handling',
    name: 'Material Handling',
    description: 'Conveyor systems and automation for material flow',
    icon: 'repeat',
    image: '/images/categories/material-handling.jpg',
  },
];
